#lang racket/base
;; curl(1) -- the everyday transfer flags and the heavily repeatable request
;; options (-H, -d, -F, -o). URLs are a 'many operand.
(require "../main.rkt")

(provide curl-cli)

(define-command-interface curl-cli
  #:names ("curl")
  (flag silent "-s" "--silent")
  (flag show-error "-S" "--show-error")
  (flag location "-L" "--location")
  (flag verbose "-v" "--verbose")
  (flag fail "-f" "--fail")
  (flag fail-with-body "--fail-with-body")
  (flag insecure "-k" "--insecure")
  (flag head "-I" "--head")
  (flag include "-i" "--include")
  (flag remote-name "-O" "--remote-name")
  (flag remote-header-name "-J" "--remote-header-name")
  (flag remote-time "-R" "--remote-time")
  (flag globoff "-g" "--globoff")
  (flag ipv4 "-4" "--ipv4")
  (flag ipv6 "-6" "--ipv6")
  (flag no-buffer "-N" "--no-buffer")
  (flag compressed "--compressed")
  (flag http1.1 "--http1.1")
  (flag http2 "--http2")
  (flag http3 "--http3")
  (flag parallel "-Z" "--parallel")
  (flag progress-bar "-#" "--progress-bar")
  (flag basic "--basic")
  (flag digest "--digest")
  (option header "-H" "--header" #:repeatable)
  (option data "-d" "--data" #:repeatable)
  (option data-raw "--data-raw" #:repeatable)
  (option data-binary "--data-binary" #:repeatable)
  (option data-urlencode "--data-urlencode" #:repeatable)
  (option form "-F" "--form" #:repeatable)
  (option output "-o" "--output" #:repeatable)
  (option request "-X" "--request")
  (option user "-u" "--user")
  (option user-agent "-A" "--user-agent")
  (option referer "-e" "--referer")
  (option cookie "-b" "--cookie")
  (option cookie-jar "-c" "--cookie-jar")
  (option upload-file "-T" "--upload-file")
  (option write-out "-w" "--write-out")
  (option max-time "-m" "--max-time")
  (option connect-timeout "--connect-timeout")
  (option retry "--retry")
  (option retry-delay "--retry-delay")
  (option max-redirs "--max-redirs")
  (option continue-at "-C" "--continue-at")
  (option range "-r" "--range")
  (option proxy "-x" "--proxy")
  (option config "-K" "--config")
  (option url "--url" #:repeatable)
  (option resolve "--resolve" #:repeatable)
  (option cacert "--cacert")
  (option capath "--capath")
  (option cert "-E" "--cert")
  (option key "--key")
  (option output-dir "--output-dir")
  (option dump-header "-D" "--dump-header")
  (option limit-rate "--limit-rate")
  (operand urls #:arity many))
