#lang racket/base
;; curl(1) -- the everyday transfer flags and the heavily repeatable request
;; options (-H, -d, -F, -o). URLs are a 'many operand.
(require (prefix-in cli: cli-spec)
         "../main.rkt")

(provide curl-cli)

(define curl-cli
  (command->interface
   (cli:cmd 'curl
     (cli:flag 'silent #:aliases '(-s --silent))
     (cli:flag 'show-error #:aliases '(-S --show-error))
     (cli:flag 'location #:aliases '(-L --location))
     (cli:flag 'verbose #:aliases '(-v --verbose))
     (cli:flag 'fail #:aliases '(-f --fail))
     (cli:flag 'fail-with-body #:aliases '(--fail-with-body))
     (cli:flag 'insecure #:aliases '(-k --insecure))
     (cli:flag 'head #:aliases '(|-I| --head))
     (cli:flag 'include #:aliases '(|-i| --include))
     (cli:flag 'remote-name #:aliases '(-O --remote-name))
     (cli:flag 'remote-header-name #:aliases '(-J --remote-header-name))
     (cli:flag 'remote-time #:aliases '(-R --remote-time))
     (cli:flag 'globoff #:aliases '(-g --globoff))
     (cli:flag 'ipv4 #:aliases '(|-4| --ipv4))
     (cli:flag 'ipv6 #:aliases '(|-6| --ipv6))
     (cli:flag 'no-buffer #:aliases '(-N --no-buffer))
     (cli:flag 'compressed #:aliases '(--compressed))
     (cli:flag 'http1.1 #:aliases '(--http1.1))
     (cli:flag 'http2 #:aliases '(--http2))
     (cli:flag 'http3 #:aliases '(--http3))
     (cli:flag 'parallel #:aliases '(-Z --parallel))
     (cli:flag 'progress-bar #:aliases '(|-#| --progress-bar))
     (cli:flag 'basic #:aliases '(--basic))
     (cli:flag 'digest #:aliases '(--digest))
     (cli:flag 'header 'string #:aliases '(-H --header) #:repeat 'list)
     (cli:flag 'data 'string #:aliases '(-d --data) #:repeat 'list)
     (cli:flag 'data-raw 'string #:aliases '(--data-raw) #:repeat 'list)
     (cli:flag 'data-binary 'string #:aliases '(--data-binary) #:repeat 'list)
     (cli:flag 'data-urlencode 'string #:aliases '(--data-urlencode) #:repeat 'list)
     (cli:flag 'form 'string #:aliases '(-F --form) #:repeat 'list)
     (cli:flag 'output 'string #:aliases '(-o --output) #:repeat 'list)
     (cli:flag 'request 'string #:aliases '(-X --request))
     (cli:flag 'user 'string #:aliases '(-u --user))
     (cli:flag 'user-agent 'string #:aliases '(-A --user-agent))
     (cli:flag 'referer 'string #:aliases '(-e --referer))
     (cli:flag 'cookie 'string #:aliases '(-b --cookie))
     (cli:flag 'cookie-jar 'string #:aliases '(-c --cookie-jar))
     (cli:flag 'upload-file 'string #:aliases '(-T --upload-file))
     (cli:flag 'write-out 'string #:aliases '(-w --write-out))
     (cli:flag 'max-time 'string #:aliases '(-m --max-time))
     (cli:flag 'connect-timeout 'string #:aliases '(--connect-timeout))
     (cli:flag 'retry 'string #:aliases '(--retry))
     (cli:flag 'retry-delay 'string #:aliases '(--retry-delay))
     (cli:flag 'max-redirs 'string #:aliases '(--max-redirs))
     (cli:flag 'continue-at 'string #:aliases '(-C --continue-at))
     (cli:flag 'range 'string #:aliases '(-r --range))
     (cli:flag 'proxy 'string #:aliases '(-x --proxy))
     (cli:flag 'config 'string #:aliases '(-K --config))
     (cli:flag 'url 'string #:aliases '(--url) #:repeat 'list)
     (cli:flag 'resolve 'string #:aliases '(--resolve) #:repeat 'list)
     (cli:flag 'cacert 'string #:aliases '(--cacert))
     (cli:flag 'capath 'string #:aliases '(--capath))
     (cli:flag 'cert 'string #:aliases '(-E --cert))
     (cli:flag 'key 'string #:aliases '(--key))
     (cli:flag 'output-dir 'string #:aliases '(--output-dir))
     (cli:flag 'dump-header 'string #:aliases '(-D --dump-header))
     (cli:flag 'limit-rate 'string #:aliases '(--limit-rate))
     (cli:arg 'urls 'string #:arity '*))))
