#lang racket/base
;; grep(1) -- the POSIX core plus the GNU/BSD spellings both implementations
;; agree on. Options where BSD and GNU disagree about taking a value (-Z)
;; are deliberately absent so they reject instead of misparsing. The pattern
;; operand slot is active only when no -e/-f supplied a pattern.
(require "../main.rkt")

(provide grep-cli)

(define-command-interface grep-cli
  #:names ("grep" "egrep" "fgrep")
  (flag recursive "-r" "--recursive")
  (flag recursive-follow "-R" "--dereference-recursive")
  (flag line-number "-n" "--line-number")
  (flag ignore-case "-i" "--ignore-case")
  (flag invert "-v" "--invert-match")
  (flag word-regexp "-w" "--word-regexp")
  (flag line-regexp "-x" "--line-regexp")
  (flag count "-c" "--count")
  (flag files-with-matches "-l" "--files-with-matches")
  (flag files-without-match "-L" "--files-without-match")
  (flag only-matching "-o" "--only-matching")
  (flag quiet "-q" "--quiet" "--silent")
  (flag no-messages "-s" "--no-messages")
  (flag with-filename "-H" "--with-filename")
  (flag no-filename "-h" "--no-filename")
  (flag byte-offset "-b" "--byte-offset")
  (flag extended-regexp "-E" "--extended-regexp")
  (flag fixed-strings "-F" "--fixed-strings")
  (flag basic-regexp "-G" "--basic-regexp")
  (flag perl-regexp "-P" "--perl-regexp")
  (flag text "-a" "--text")
  (flag skip-binary "-I")
  (flag null-data "-z" "--null-data")
  (option pattern "-e" "--regexp" #:repeatable)
  (option pattern-file "-f" "--file" #:repeatable)
  (option after-context "-A" "--after-context")
  (option before-context "-B" "--before-context")
  (option context "-C" "--context")
  (option max-count "-m" "--max-count")
  (option directories "-d" "--directories")
  (option devices "-D" "--devices")
  (option include "--include" #:repeatable)
  (option exclude "--exclude" #:repeatable)
  (option include-dir "--include-dir" #:repeatable)
  (option exclude-dir "--exclude-dir" #:repeatable)
  (option binary-files "--binary-files")
  (option label "--label")
  (option color "--color" #:optional-value)
  (option colour "--colour" #:optional-value)
  (operand pattern-operand #:arity one
           #:unless (lambda (inv)
                      (or (invocation-has-option? inv 'pattern)
                          (invocation-has-option? inv 'pattern-file))))
  (operand files #:arity many))
