#lang racket/base
;; rg(1), ripgrep -- the flags and options a grep translation or an rg
;; rewrite is likely to meet. Unlike grep, --color requires a value.
(require "../main.rkt")

(provide rg-cli)

(define-command-interface rg-cli
  #:names ("rg")
  (flag ignore-case "-i" "--ignore-case")
  (flag smart-case "-S" "--smart-case")
  (flag case-sensitive "-s" "--case-sensitive")
  (flag invert "-v" "--invert-match")
  (flag word-regexp "-w" "--word-regexp")
  (flag line-regexp "-x" "--line-regexp")
  (flag line-number "-n" "--line-number")
  (flag no-line-number "-N" "--no-line-number")
  (flag count "-c" "--count")
  (flag count-matches "--count-matches")
  (flag include-zero "--include-zero")
  (flag files-with-matches "-l" "--files-with-matches")
  (flag files-without-match "--files-without-match")
  (flag only-matching "-o" "--only-matching")
  (flag quiet "-q" "--quiet")
  (flag hidden "--hidden")
  (flag no-ignore "--no-ignore")
  (flag unrestricted "-u" "--unrestricted")
  (flag fixed-strings "-F" "--fixed-strings")
  (flag pcre2 "-P" "--pcre2")
  (flag multiline "-U" "--multiline")
  (flag search-zip "-z" "--search-zip")
  (flag text "-a" "--text")
  (flag follow "-L" "--follow")
  (flag with-filename "-H" "--with-filename")
  (flag no-filename "-I" "--no-filename")
  (flag no-messages "--no-messages")
  (flag byte-offset "-b" "--byte-offset")
  (flag heading "--heading")
  (flag no-heading "--no-heading")
  (flag pretty "-p" "--pretty")
  (flag vimgrep "--vimgrep")
  (flag json "--json")
  (flag null "-0" "--null")
  (flag files "--files")
  (option pattern "-e" "--regexp" #:repeatable)
  (option pattern-file "-f" "--file" #:repeatable)
  (option after-context "-A" "--after-context")
  (option before-context "-B" "--before-context")
  (option context "-C" "--context")
  (option max-count "-m" "--max-count")
  (option glob "-g" "--glob" #:repeatable)
  (option iglob "--iglob" #:repeatable)
  (option type "-t" "--type" #:repeatable)
  (option type-not "-T" "--type-not" #:repeatable)
  (option type-add "--type-add" #:repeatable)
  (option threads "-j" "--threads")
  (option max-depth "--max-depth")
  (option max-filesize "--max-filesize")
  (option encoding "-E" "--encoding")
  (option replace "-r" "--replace")
  (option sort "--sort" #:values ("none" "path" "modified" "accessed" "created"))
  (option sortr "--sortr" #:values ("none" "path" "modified" "accessed" "created"))
  (option color "--color" #:values ("never" "auto" "always" "ansi"))
  (option colors "--colors" #:repeatable)
  (operand pattern-operand #:arity one
           #:unless (lambda (inv)
                      (or (invocation-has-option? inv 'pattern)
                          (invocation-has-option? inv 'pattern-file)
                          (invocation-has-flag? inv 'files))))
  (operand paths #:arity many))
