#lang racket/base
;; systemctl(1) -- global flags and options are declared at the top level
;; and stay matchable before or after the subcommand word (`systemctl --user
;; enable --now foo` and `systemctl enable --now --user foo` both parse);
;; each subcommand contributes its own operands.
(require "../main.rkt")

(provide systemctl-cli)

(define-command-interface systemctl-cli
  #:names ("systemctl")
  (flag user "--user")
  (flag system "--system")
  (flag now "--now")
  (flag quiet "-q" "--quiet")
  (flag no-pager "--no-pager")
  (flag no-block "--no-block")
  (flag no-reload "--no-reload")
  (flag force "-f" "--force")
  (flag full "-l" "--full")
  (flag all "-a" "--all")
  (flag failed "--failed")
  (flag global "--global")
  (flag runtime "--runtime")
  (flag follow "--follow")
  (flag value-only "--value")
  (option type "-t" "--type")
  (option state "--state")
  (option property "-p" "--property" #:repeatable)
  (option signal "-s" "--signal")
  (option host "-H" "--host")
  (option machine "-M" "--machine")
  (option output "-o" "--output")
  (option lines "-n" "--lines")
  (option root "--root")
  (option job-mode "--job-mode")
  (option preset-mode "--preset-mode")
  (subcommand "start" (operand units #:arity many))
  (subcommand "stop" (operand units #:arity many))
  (subcommand "restart" (operand units #:arity many))
  (subcommand "try-restart" (operand units #:arity many))
  (subcommand "reload" (operand units #:arity many))
  (subcommand "reload-or-restart" (operand units #:arity many))
  (subcommand "kill" (operand units #:arity many))
  (subcommand "status" (operand units #:arity many))
  (subcommand "is-active" (operand units #:arity many))
  (subcommand "is-enabled" (operand units #:arity many))
  (subcommand "is-failed" (operand units #:arity many))
  (subcommand "enable" (operand units #:arity many))
  (subcommand "disable" (operand units #:arity many))
  (subcommand "mask" (operand units #:arity many))
  (subcommand "unmask" (operand units #:arity many))
  (subcommand "preset" (operand units #:arity many))
  (subcommand "reset-failed" (operand units #:arity many))
  (subcommand "cat" (operand units #:arity many))
  (subcommand "show" (operand units #:arity many))
  (subcommand "edit" (operand units #:arity many))
  (subcommand "list-units" (operand patterns #:arity many))
  (subcommand "list-unit-files" (operand patterns #:arity many))
  (subcommand "list-sockets" (operand patterns #:arity many))
  (subcommand "list-timers" (operand patterns #:arity many))
  (subcommand "list-dependencies" (operand unit #:arity optional))
  (subcommand "isolate" (operand unit #:arity one))
  (subcommand "set-default" (operand unit #:arity one))
  (subcommand "get-default")
  (subcommand "daemon-reload")
  (subcommand "daemon-reexec"))
