#lang racket/base
;; systemctl(1) -- global flags and options are declared at the top level
;; and stay matchable before or after the subcommand word (`systemctl --user
;; enable --now foo` and `systemctl enable --now --user foo` both parse);
;; each subcommand contributes its own operands.
(require (prefix-in cli: cli-spec)
         "../main.rkt")

(provide systemctl-cli)

(define systemctl-cli
  (command->interface
   (cli:cmd 'systemctl
     (cli:flag 'user #:aliases '(--user))
     (cli:flag 'system #:aliases '(--system))
     (cli:flag 'now #:aliases '(--now))
     (cli:flag 'quiet #:aliases '(-q --quiet))
     (cli:flag 'no-pager #:aliases '(--no-pager))
     (cli:flag 'no-block #:aliases '(--no-block))
     (cli:flag 'no-reload #:aliases '(--no-reload))
     (cli:flag 'force #:aliases '(-f --force))
     (cli:flag 'full #:aliases '(-l --full))
     (cli:flag 'all #:aliases '(-a --all))
     (cli:flag 'failed #:aliases '(--failed))
     (cli:flag 'global #:aliases '(--global))
     (cli:flag 'runtime #:aliases '(--runtime))
     (cli:flag 'follow #:aliases '(--follow))
     (cli:flag 'value-only #:aliases '(--value))
     (cli:flag 'type 'string #:aliases '(-t --type))
     (cli:flag 'state 'string #:aliases '(--state))
     (cli:flag 'property 'string #:aliases '(-p --property) #:repeat 'list)
     (cli:flag 'signal 'string #:aliases '(-s --signal))
     (cli:flag 'host 'string #:aliases '(-H --host))
     (cli:flag 'machine 'string #:aliases '(-M --machine))
     (cli:flag 'output 'string #:aliases '(-o --output))
     (cli:flag 'lines 'string #:aliases '(-n --lines))
     (cli:flag 'root 'string #:aliases '(--root))
     (cli:flag 'job-mode 'string #:aliases '(--job-mode))
     (cli:flag 'preset-mode 'string #:aliases '(--preset-mode))
     (cli:subcommand 'start (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'stop (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'restart (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'try-restart (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'reload (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'reload-or-restart (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'kill (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'status (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'is-active (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'is-enabled (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'is-failed (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'enable (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'disable (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'mask (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'unmask (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'preset (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'reset-failed (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'cat (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'show (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'edit (cli:arg 'units 'string #:arity '*))
     (cli:subcommand 'list-units (cli:arg 'patterns 'string #:arity '*))
     (cli:subcommand 'list-unit-files (cli:arg 'patterns 'string #:arity '*))
     (cli:subcommand 'list-sockets (cli:arg 'patterns 'string #:arity '*))
     (cli:subcommand 'list-timers (cli:arg 'patterns 'string #:arity '*))
     (cli:subcommand 'list-dependencies (cli:arg 'unit 'string #:arity '?))
     (cli:subcommand 'isolate (cli:arg 'unit 'string))
     (cli:subcommand 'set-default (cli:arg 'unit 'string))
     (cli:subcommand 'get-default)
     (cli:subcommand 'daemon-reload)
     (cli:subcommand 'daemon-reexec))))
